#!/usr/bin/env python3
"""Appends shop, search, confirm, preview, task integration to game.js."""
import pathlib

P = pathlib.Path(__file__).parent / "miniapp" / "static" / "game.js"
NL = chr(10)
DQ = chr(34)
SQ = chr(39)

BLOCK = NL.join([
    "",
    "/* ============ SHOP ============ */",
    "function loadShop() {",
    "  loadShopFeatured(); loadShopCases();",
    "}",
    "function loadShopFeatured() {",
    '  const g = $("shop-featured"); if (!g) return;',
    '  g.innerHTML = Object.entries(BOXES_DATA).slice(-2).map(([id, b]) =>',
    "    `<div class=//'featured-card//' onclick=//'showCasePreview(/"${id}/")//'>",
    "      <span class=//'case-emoji//'>${b.emoji}</span>",
    "      <h3>${b.name}</h3>",
    "      <div class=//'case-price//'>💎 ${b.price.toLocaleString()}</div>",
    "    </div>`").join('');",
    "}",
    "function loadShopCases() {",
    '  const g = $("shop-cases"); if (!g) return;',
    '  g.innerHTML = Object.entries(BOXES_DATA).map(([id, b]) =>',
    "    `<div class=//'case-card//' style=//'--glow:${b.color}44//' onclick=//'showCasePreview(/"${id}/")//'>",
    "      <span class=//'case-emoji//'>${b.emoji}</span>",
    "      <h3>${b.name.replace(/ Box/, '')}</h3>",
    "      <div class=//'case-price//'>💎 ${b.price.toLocaleString()}</div>",
    "    </div>`").join('');",
    "}",
    "",
    "/* ============ CASE PREVIEW ============ */",
    "function showCasePreview(id) {",
    "  const b = BOXES_DATA[id]; if (!b) return;",
    '  $("preview-emoji").textContent = b.emoji;',
    '  $("preview-name").textContent = b.name;',
    '  $("preview-price").textContent = b.price.toLocaleString();',
    '  $("preview-open-btn").dataset.case = id;',
    '  $("preview-rewards").innerHTML = b.items.map(it =>',
    "    `<div class=//'preview-reward//'>",
    "      <span class=//'r-emoji//'>${it.emoji}</span>",
    "      <div class=//'r-info//'><div class=//'r-name//'>${it.name}</div><div class=//'r-chance//'>${it.chance}% chance</div></div>",
    "      <div class=//'r-val//'>💎${it.value.toLocaleString()}</div>",
    "    </div>`).join('');",
    '  $("preview-modal").classList.remove("hidden");',
    "}",
    "function closePreview() { $('preview-modal').classList.add('hidden'); }",
    "",
    "/* ============ CONFIRM FLOW ============ */",
    "let pendingCase = null;",
    "function confirmOpenBox() {",
    "  closePreview();",
    '  const id = $("preview-open-btn").dataset.case || pendingCase;',
    "  const b = BOXES_DATA[id]; if (!b) return;",
    "  pendingCase = id;",
    '  $("confirm-emoji").textContent = b.emoji;',
    '  $("confirm-text").textContent = "Open " + b.name + "?";',
    '  $("confirm-sub").textContent = "Cost: " + b.price.toLocaleString() + " 💎 | Balance: " + gems.toLocaleString();',
    '  $("confirm-modal").classList.remove("hidden");',
    "}",
    "async function executeConfirm() {",
    "  closeConfirm();",
    "  if (!pendingCase) return;",
    "  await openBox(pendingCase);",
    "  pendingCase = null;",
    "}",
    "function closeConfirm() { $('confirm-modal').classList.add('hidden'); }",
    "",
    "/* ============ MARKETPLACE SEARCH + SORT ============ */",
    "let marketSearch = '';",
    "let marketSort = 'newest';",
    "function searchMarket(q) { marketSearch = q.toLowerCase(); renderMarket(); }",
    "function sortMarket(s) { marketSort = s; renderMarket(); }",
    "let marketData = [];",
    "async function loadMarket() {",
    "  try {",
    "    const r = await fetch('/api/marketplace');",
    "    const d = await r.json();",
    "    marketData = d.listings || [];",
    "    renderMarket();",
    "  } catch (e) {",
    "    const g = $('market-list');",
    "    if (g) g.innerHTML = '<p class=/"empty/">Market unavailable</p>';",
    "  }",
    "}",
    "function renderMarket() {",
    "  const g = $('market-list'); if (!g) return;",
    "  let items = [...marketData];",
    "  // search filter",
    "  if (marketSearch) {",
    "    items = items.filter(l => {",
    "      const hay = (l.item.name + ' ' + l.item.rarity).toLowerCase();",
    "      return hay.indexOf(marketSearch) >= 0;",
    "    });",
    "  }",
    "  // sort",
    "  if (marketSort === 'cheapest') items.sort((a, b) => (a.price || 0) - (b.price || 0));",
    "  else if (marketSort === 'expensive') items.sort((a, b) => (b.price || 0) - (a.price || 0));",
    "  // newest = default order (server returns desc)",
    "  g.innerHTML = items.length ? items.map(l =>",
    "    `<div class=/"inv-item/" data-rarity=/"${l.item.rarity}/" onclick=/"showItem(${JSON.stringify({emoji:l.item.emoji,name:l.item.name,rarity:l.item.rarity,value:l.price}).replace(//"/g,'&quot;')})/">",
    "      <span class=/"rarity-tag/" data-r=/"${l.item.rarity}/">${l.item.rarity}</span>",
    "      <span class=/"item-icon/">${l.item.emoji || '🎁'}</span>",
    "      <h4>${l.item.name}</h4>",
    "      <p class=/"item-value/">💎 ${(l.price || 0).toLocaleString()}</p>",
    "    </div>`).join('') : '<p class=/"empty/">No listings match your search</p>';",
    "}",
    "",
    "/* ============ ENHANCED INVENTORY (rarity data attrs) ============ */",
    "function renderInv() {",
    "  const g = $('inventory-list'); if (!g) return;",
    "  const ord = ['common','uncommon','rare','epic','legendary','mythic','divine'];",
    "  let items = invCache;",
    "  if (invFilter !== 'all') { const mi = ord.indexOf(invFilter); items = items.filter(i => ord.indexOf(i.rarity) >= mi); }",
    "  g.innerHTML = items.length ? items.map(i =>",
    "    `<div class=/"inv-item/" data-rarity=/"${i.rarity}/" onclick='showItem(${JSON.stringify(i).replace(//"/g,'&quot;')})'>",
    "      <span class=/"rarity-tag/" data-r=/"${i.rarity}/">${i.rarity}</span>",
    "      <span class=/"item-icon/">${i.emoji || '🎁'}</span>",
    "      <h4>${i.name}</h4>",
    "      <p class=/"item-value/">💎 ${(i.value || 0).toLocaleString()}</p>",
    "    </div>`).join('') : '<p class=/"empty/">No items yet</p>';",
    "}",
    "",
    "/* ============ ENHANCED ITEM DETAIL ============ */",
    "function showItem(it) {",
    "  $('detail-emoji').textContent = it.emoji || '🎁';",
    "  $('detail-name').textContent = it.name;",
    "  $('detail-rarity').textContent = it.rarity;",
    "  $('detail-rarity').style.color = RC[it.rarity] || '#fff';",
    "  $('detail-value').textContent = '💎 ' + (it.value || 0).toLocaleString();",
    '  $("detail-meta").innerHTML = `',
    '    <div class="dm-row"><span>Rarity</span><b>${it.rarity}</b></div>',
    '    <div class="dm-row"><span>Est. Value</span><b>💎 ${(it.value||0).toLocaleString()}</b></div>',
    '    <div class="dm-row"><span>Acquired</span><b>${it.acquired_at ? ' + "new Date(it.acquired_at).toLocaleDateString()" + ' : '-'}</b></div>',
    '    <div class="dm-row"><span>Tradeable</span><b>${it.is_locked ? '🔒 Locked' : '✅ Yes'}</b></div>',
    '`;',
    '  $("item-modal").classList.remove("hidden");',
    "}",
    "",
    "/* ============ TASK INTEGRATION ============ */",
    "const TASKS_DATA = [",
    "  {id:'daily_drop',cat:'daily',name:'Claim Daily Reward',reward:50,type:'action',fn:claimDaily},",
    "  {id:'open_box',cat:'daily',name:'Open 1 Mystery Box',reward:100,type:'box_opened',need:1},",
    "  {id:'spin_wheel',cat:'daily',name:'Spin the Gift Wheel',reward:80,type:'wheel_spin',need:1},",
    "  {id:'join_channel',cat:'social',name:'Join our channel',reward:200,type:'channel',url:'https://t.me/FrogCaseHelp'},",
    "  {id:'follow_bot',cat:'social',name:'Follow the bot',reward:100,type:'channel',url:'https://t.me/MyCasinoBotx_bot'},",
    "  {id:'ref_1',cat:'referral',name:'Invite 1 friend',reward:150,type:'referrals',need:1},",
    "  {id:'ref_5',cat:'referral',name:'Invite 5 friends',reward:750,type:'referrals',need:5},",
    "  {id:'ref_25',cat:'referral',name:'Invite 25 friends',reward:3000,type:'referrals',need:25},",
    "];",
    "async function loadTasks() {",
    "  const stats = await api('/api/stats', {user_id: uid});",
    "  const groups = {daily:[], social:[], referral:[]};",
    "  TASKS_DATA.forEach(t => {",
    "    let progress = 0, done = false;",
    "    if (t.type === 'daily') done = (stats.streak || 0) > 0;",
    "    if (t.type === 'box_opened') progress = stats.cases_opened || 0;",
    "    if (t.type === 'wheel_spin') progress = stats.wheel_spins || 0;",
    "    if (t.type === 'referrals') progress = stats.total_referrals || 0;",
    "    if (progress >= (t.need || 1)) done = true;",
    "    groups[t.cat].push({...t, progress: Math.min(progress, t.need || 1), done});",
    "  });",
    "  ['daily','social','referral'].forEach(cat => {",
    "    const el = $('daily-tasks'); const map = {daily:'daily-tasks',social:'social-tasks',referral:'ref-tasks'};",
    "    const container = $(map[cat]);",
    "    if (!container) return;",
    "    if (!groups[cat].length) { container.innerHTML = '<p class=/"empty/">No tasks available</p>'; return; }",
    "    container.innerHTML = groups[cat].map(t => {",
    "      const bar = t.need > 1 ? `<div class=//'task-progress//'><div class=//'task-prog-fill//' style=//'width:${Math.min(100,(t.progress/t.need)*100)}%//'></div></div>` : '';",
    "      return `<div class=/"task-row/">",
    "        <div class=/"task-info/"><b>${t.name}</b><small>💎 ${t.reward} gems ${t.need > 1 ? '(' + t.progress + '/' + t.need + ')' : ''}</small>${bar}</div>",
    "        <button class=/"task-btn ${t.done ? 'done' : ''}/" onclick=/"doTask(${JSON.stringify(t).replace(//"/g,'&quot;')})/">${t.done ? 'DONE' : (t.url ? 'OPEN' : (t.fn ? 'CLAIM' : t.progress >= (t.need||1) ? 'CLAIM' : 'GO'))}</button>",
    "      </div>`;",
    "    }).join('');",
    "  });",
    "}",
    "async function doTask(t) {",
    "  if (t.url) { window.open(t.url, '_blank'); toast('Open the link then return'); return; }",
    "  if (t.fn) { await t.fn(); loadTasks(); return; }",
    "  toast('Navigate to the action to complete this task');",
    "}",
    "",
    "/* ============ ENHANCED CASE OPEN (use confirm) ============ */",
    "function openBox(id) {",
    "  // bypass confirm for direct calls (from confirm modal)",
    "  spinsActive = true; haptic();",
    "  const promise = api('/api/case/open', {user_id: uid, case_id: id});",
    "  handleCaseResult(promise);",
    "}",
    "async function handleCaseResult(promise) {",
    "  const r = await promise;",
    "  if (!r.success) { spinsActive = false; toast(r.message || 'Not enough gems'); return; }",
    "  const strip = $('roll-strip'); strip.style.transition = 'none'; strip.style.transform = 'translateX(0)'; strip.innerHTML = '';",
    "  const pool = []; Object.values(BOXES_DATA).forEach(b => b.items.forEach(i => pool.push(i)));",
    "  const WIN = 24;",
    "  for (let i = 0; i < 34; i++) {",
    "    const it = i === WIN ? r.item : pool[Math.floor(Math.random() * pool.length)];",
    "    strip.innerHTML += `<div class=/"roll-item/" style=/"--rc:${RC[it.rarity] || '#333'}/">${it.emoji || '🎁'}</div>`;",
    "  }",
    "  $('case-modal').classList.remove('hidden');",
    "  $('reveal-card').classList.add('hidden');",
    "  requestAnimationFrame(() => {",
    "    const tw = 108; strip.style.transition = 'transform 3.5s cubic-bezier(.12,.78,.15,1)';",
    "    strip.style.transform = `translateX(${-(WIN * tw) + 158 + Math.random() * 36}px)`;",
    "  });",
    "  setTimeout(() => {",
    "    const it = r.item;",
    "    $('revealed-item').textContent = it.emoji || '🎁';",
    "    $('item-name').textContent = it.name;",
    "    $('item-rarity').textContent = it.rarity;",
    "    $('item-rarity').style.color = RC[it.rarity] || '#fff';",
    "    $('item-value').textContent = '💎 ' + (it.value || 0).toLocaleString();",
    "    $('reveal-card').classList.remove('hidden');",
    "    setGems(r.balance); haptic((it.value || 0) >= 2000 ? 'win' : '');",
    "    spinsActive = false; loadTasks();",
    "  }, 3700);",
    "}",
])

s = P.read_text(encoding="utf-8")
if "SHOP" in s and len(s) > 4000:
    print("[skip] v9 features already appended")
else:
    P.write_text(s + BLOCK + NL, encoding="utf-8")
    print("[ok] shop + search + confirm + preview + tasks appended")
